### ISSUE TITLE
x64 support！

### ISSUE THREAD

**Issue by caizhe666** [m0n0ph1/Process-Hollowing#5]
I tried to migrate the code to x64 platform. I revised the structure definition in x86 and x64, and also tried to repair and relocate. The program seemed to succeed, but the process was not started.

**Comment by CCCougar** [comment]
You may find what you want here: [https://github.com/idan1288/ProcessHollowing32-64](https://github.com/idan1288/ProcessHollowing32-64)

**Comment by caizhe666** [comment]
> You may find what you want here: https://github.com/idan1288/ProcessHollowing32-64

thanks a lot!
